/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PossessionRouteImport } from './routes/possession'
import { Route as ReraRouteImport } from './routes/rera'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as CallingAgentIndexRouteImport } from './routes/calling-agent.index'
import { Route as CallingAgentCallIdRouteImport } from './routes/calling-agent.$callId'
import { Route as CustomerDashboardRouteImport } from './routes/customer.dashboard'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as PartnersIndexRouteImport } from './routes/partners.index'
import { Route as PartnersPartnerIdRouteImport } from './routes/partners.$partnerId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PossessionRoute = PossessionRouteImport.update({
  id: '/possession',
  path: '/possession',
  getParentRoute: () => rootRouteImport,
} as any)
const ReraRoute = ReraRouteImport.update({
  id: '/rera',
  path: '/rera',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CallingAgentIndexRoute = CallingAgentIndexRouteImport.update({
  id: '/calling-agent/',
  path: '/calling-agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallingAgentCallIdRoute = CallingAgentCallIdRouteImport.update({
  id: '/calling-agent/$callId',
  path: '/calling-agent/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer/dashboard',
  path: '/customer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersIndexRoute = PartnersIndexRouteImport.update({
  id: '/partners/',
  path: '/partners/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersPartnerIdRoute = PartnersPartnerIdRouteImport.update({
  id: '/partners/$partnerId',
  path: '/partners/$partnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/payments': typeof PaymentsRoute
  '/possession': typeof PossessionRoute
  '/rera': typeof ReraRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/calling-agent/$callId': typeof CallingAgentCallIdRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/calling-agent/': typeof CallingAgentIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/payments': typeof PaymentsRoute
  '/possession': typeof PossessionRoute
  '/rera': typeof ReraRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/calling-agent/$callId': typeof CallingAgentCallIdRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/bookings': typeof BookingsIndexRoute
  '/calling-agent': typeof CallingAgentIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/partners': typeof PartnersIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/commissions': typeof CommissionsRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/inventory': typeof InventoryRoute
  '/payments': typeof PaymentsRoute
  '/possession': typeof PossessionRoute
  '/rera': typeof ReraRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/calling-agent/$callId': typeof CallingAgentCallIdRoute
  '/customer/dashboard': typeof CustomerDashboardRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/partners/$partnerId': typeof PartnersPartnerIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/bookings/': typeof BookingsIndexRoute
  '/calling-agent/': typeof CallingAgentIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/partners/': typeof PartnersIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/audit'
    | '/commissions'
    | '/dashboard'
    | '/documents'
    | '/inventory'
    | '/payments'
    | '/possession'
    | '/rera'
    | '/bookings/$bookingId'
    | '/calling-agent/$callId'
    | '/customer/dashboard'
    | '/leads/$leadId'
    | '/partners/$partnerId'
    | '/projects/$projectId'
    | '/bookings/'
    | '/calling-agent/'
    | '/leads/'
    | '/partners/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/audit'
    | '/commissions'
    | '/dashboard'
    | '/documents'
    | '/inventory'
    | '/payments'
    | '/possession'
    | '/rera'
    | '/bookings/$bookingId'
    | '/calling-agent/$callId'
    | '/customer/dashboard'
    | '/leads/$leadId'
    | '/partners/$partnerId'
    | '/projects/$projectId'
    | '/bookings'
    | '/calling-agent'
    | '/leads'
    | '/partners'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/audit'
    | '/commissions'
    | '/dashboard'
    | '/documents'
    | '/inventory'
    | '/payments'
    | '/possession'
    | '/rera'
    | '/bookings/$bookingId'
    | '/calling-agent/$callId'
    | '/customer/dashboard'
    | '/leads/$leadId'
    | '/partners/$partnerId'
    | '/projects/$projectId'
    | '/bookings/'
    | '/calling-agent/'
    | '/leads/'
    | '/partners/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  CommissionsRoute: typeof CommissionsRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  InventoryRoute: typeof InventoryRoute
  PaymentsRoute: typeof PaymentsRoute
  PossessionRoute: typeof PossessionRoute
  ReraRoute: typeof ReraRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  CallingAgentCallIdRoute: typeof CallingAgentCallIdRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  PartnersPartnerIdRoute: typeof PartnersPartnerIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CallingAgentIndexRoute: typeof CallingAgentIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  PartnersIndexRoute: typeof PartnersIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/possession': {
      id: '/possession'
      path: '/possession'
      fullPath: '/possession'
      preLoaderRoute: typeof PossessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rera': {
      id: '/rera'
      path: '/rera'
      fullPath: '/rera'
      preLoaderRoute: typeof ReraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calling-agent/': {
      id: '/calling-agent/'
      path: '/calling-agent'
      fullPath: '/calling-agent/'
      preLoaderRoute: typeof CallingAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calling-agent/$callId': {
      id: '/calling-agent/$callId'
      path: '/calling-agent/$callId'
      fullPath: '/calling-agent/$callId'
      preLoaderRoute: typeof CallingAgentCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/dashboard': {
      id: '/customer/dashboard'
      path: '/customer/dashboard'
      fullPath: '/customer/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/': {
      id: '/partners/'
      path: '/partners'
      fullPath: '/partners/'
      preLoaderRoute: typeof PartnersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$partnerId': {
      id: '/partners/$partnerId'
      path: '/partners/$partnerId'
      fullPath: '/partners/$partnerId'
      preLoaderRoute: typeof PartnersPartnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  CommissionsRoute: CommissionsRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  InventoryRoute: InventoryRoute,
  PaymentsRoute: PaymentsRoute,
  PossessionRoute: PossessionRoute,
  ReraRoute: ReraRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  CallingAgentCallIdRoute: CallingAgentCallIdRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  PartnersPartnerIdRoute: PartnersPartnerIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CallingAgentIndexRoute: CallingAgentIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  PartnersIndexRoute: PartnersIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
