/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CallingAgentIndexRouteImport } from './routes/calling-agent.index'
import { Route as CallingAgentCallIdRouteImport } from './routes/calling-agent.$callId'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as LeadsLeadIdRouteImport } from './routes/leads.$leadId'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CallingAgentIndexRoute = CallingAgentIndexRouteImport.update({
  id: '/calling-agent/',
  path: '/calling-agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallingAgentCallIdRoute = CallingAgentCallIdRouteImport.update({
  id: '/calling-agent/$callId',
  path: '/calling-agent/$callId',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsLeadIdRoute = LeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/calling-agent/$callId': typeof CallingAgentCallIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/calling-agent/': typeof CallingAgentIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/calling-agent/$callId': typeof CallingAgentCallIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/calling-agent': typeof CallingAgentIndexRoute
  '/leads': typeof LeadsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-insights': typeof AiInsightsRoute
  '/approvals': typeof ApprovalsRoute
  '/dashboard': typeof DashboardRoute
  '/inventory': typeof InventoryRoute
  '/calling-agent/$callId': typeof CallingAgentCallIdRoute
  '/leads/$leadId': typeof LeadsLeadIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/calling-agent/': typeof CallingAgentIndexRoute
  '/leads/': typeof LeadsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/calling-agent/$callId'
    | '/leads/$leadId'
    | '/projects/$projectId'
    | '/calling-agent/'
    | '/leads/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/calling-agent/$callId'
    | '/leads/$leadId'
    | '/projects/$projectId'
    | '/calling-agent'
    | '/leads'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/ai-insights'
    | '/approvals'
    | '/dashboard'
    | '/inventory'
    | '/calling-agent/$callId'
    | '/leads/$leadId'
    | '/projects/$projectId'
    | '/calling-agent/'
    | '/leads/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiInsightsRoute: typeof AiInsightsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  DashboardRoute: typeof DashboardRoute
  InventoryRoute: typeof InventoryRoute
  CallingAgentCallIdRoute: typeof CallingAgentCallIdRoute
  LeadsLeadIdRoute: typeof LeadsLeadIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  CallingAgentIndexRoute: typeof CallingAgentIndexRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calling-agent/': {
      id: '/calling-agent/'
      path: '/calling-agent'
      fullPath: '/calling-agent/'
      preLoaderRoute: typeof CallingAgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calling-agent/$callId': {
      id: '/calling-agent/$callId'
      path: '/calling-agent/$callId'
      fullPath: '/calling-agent/$callId'
      preLoaderRoute: typeof CallingAgentCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/$leadId': {
      id: '/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/leads/$leadId'
      preLoaderRoute: typeof LeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiInsightsRoute: AiInsightsRoute,
  ApprovalsRoute: ApprovalsRoute,
  DashboardRoute: DashboardRoute,
  InventoryRoute: InventoryRoute,
  CallingAgentCallIdRoute: CallingAgentCallIdRoute,
  LeadsLeadIdRoute: LeadsLeadIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  CallingAgentIndexRoute: CallingAgentIndexRoute,
  LeadsIndexRoute: LeadsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
